//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatBeats.Framework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlatBeats.Framework.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create account.
        /// </summary>
        public static string Command_CreateAccount {
            get {
                return ResourceManager.GetString("Command_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email mix.
        /// </summary>
        public static string Command_EmailMix {
            get {
                return ResourceManager.GetString("Command_EmailMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to follow.
        /// </summary>
        public static string Command_FollowUser {
            get {
                return ResourceManager.GetString("Command_FollowUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like.
        /// </summary>
        public static string Command_LikeMix {
            get {
                return ResourceManager.GetString("Command_LikeMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string Command_Login {
            get {
                return ResourceManager.GetString("Command_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string Command_Logout {
            get {
                return ResourceManager.GetString("Command_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Command_NextTrack {
            get {
                return ResourceManager.GetString("Command_NextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string Command_PauseMix {
            get {
                return ResourceManager.GetString("Command_PauseMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string Command_PinToStart {
            get {
                return ResourceManager.GetString("Command_PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string Command_PlayMix {
            get {
                return ResourceManager.GetString("Command_PlayMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review mix.
        /// </summary>
        public static string Command_ReviewMix {
            get {
                return ResourceManager.GetString("Command_ReviewMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share mix.
        /// </summary>
        public static string Command_ShareMix {
            get {
                return ResourceManager.GetString("Command_ShareMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unfollow.
        /// </summary>
        public static string Command_UnfollowUser {
            get {
                return ResourceManager.GetString("Command_UnfollowUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlike.
        /// </summary>
        public static string Command_UnlikeMix {
            get {
                return ResourceManager.GetString("Command_UnlikeMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin from start.
        /// </summary>
        public static string Command_UnpinStart {
            get {
                return ResourceManager.GetString("Command_UnpinStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix: {0}
        ///Description:
        ///{1}
        ///Link:
        ///{2}.
        /// </summary>
        public static string EmailBody_ShareMix {
            get {
                return ResourceManager.GetString("EmailBody_ShareMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out this 8tracks.com mix!.
        /// </summary>
        public static string EmailSubject_ShareMix {
            get {
                return ResourceManager.GetString("EmailSubject_ShareMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are having a disagreement with the server by attempting this, please report this if it continues to happen..
        /// </summary>
        public static string Error_BadRequest_Message {
            get {
                return ResourceManager.GetString("Error_BadRequest_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We made a bad request.
        /// </summary>
        public static string Error_BadRequest_Title {
            get {
                return ResourceManager.GetString("Error_BadRequest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we can&apos;t connect to the network, maybe check your internet connection or try again a bit later..
        /// </summary>
        public static string Error_NoNetwork_Message {
            get {
                return ResourceManager.GetString("Error_NoNetwork_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where did the internet go?.
        /// </summary>
        public static string Error_NoNetwork_Title {
            get {
                return ResourceManager.GetString("Error_NoNetwork_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we can&apos;t communicate with the server at the moment, please check your internet connection or try again later..
        /// </summary>
        public static string Error_ServerUnavailable_Message {
            get {
                return ResourceManager.GetString("Error_ServerUnavailable_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server unavailable.
        /// </summary>
        public static string Error_ServerUnavailable_Title {
            get {
                return ResourceManager.GetString("Error_ServerUnavailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either your UserName is wrong, or you miss-typed your password, feel free to try again..
        /// </summary>
        public static string Error_SignInFailed_Message {
            get {
                return ResourceManager.GetString("Error_SignInFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Try again.
        /// </summary>
        public static string Error_SignInFailed_Title {
            get {
                return ResourceManager.GetString("Error_SignInFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something really unexpected happened! Please report this when you are asked, next time you run this app..
        /// </summary>
        public static string Error_UnknownError_Message {
            get {
                return ResourceManager.GetString("Error_UnknownError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        public static string Error_UnknownError_Title {
            get {
                return ResourceManager.GetString("Error_UnknownError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Censor mixes with explicit artwork + language.
        /// </summary>
        public static string Label_CensorshipEnabled {
            get {
                return ResourceManager.GetString("Label_CensorshipEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading more....
        /// </summary>
        public static string Label_LoadingMore1 {
            get {
                return ResourceManager.GetString("Label_LoadingMore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading even more....
        /// </summary>
        public static string Label_LoadingMore2 {
            get {
                return ResourceManager.GetString("Label_LoadingMore2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading even more still....
        /// </summary>
        public static string Label_LoadingMore3 {
            get {
                return ResourceManager.GetString("Label_LoadingMore3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a lot isn&apos;t there?.
        /// </summary>
        public static string Label_LoadingMore4 {
            get {
                return ResourceManager.GetString("Label_LoadingMore4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found what you&apos;re looking for?.
        /// </summary>
        public static string Label_LoadingMore5 {
            get {
                return ResourceManager.GetString("Label_LoadingMore5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any minute now....
        /// </summary>
        public static string Label_LoadingMore6 {
            get {
                return ResourceManager.GetString("Label_LoadingMore6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;d hate to scroll to the top right now....
        /// </summary>
        public static string Label_LoadingMore7 {
            get {
                return ResourceManager.GetString("Label_LoadingMore7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just let me know when you&apos;re done....
        /// </summary>
        public static string Label_LoadingMore8 {
            get {
                return ResourceManager.GetString("Label_LoadingMore8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to play similar mixes.
        /// </summary>
        public static string Label_PlayNextMix {
            get {
                return ResourceManager.GetString("Label_PlayNextMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play only when connected to WIFI.
        /// </summary>
        public static string Label_PlayOverWifiOnly {
            get {
                return ResourceManager.GetString("Label_PlayOverWifiOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on home page:.
        /// </summary>
        public static string Label_PreferredList {
            get {
                return ResourceManager.GetString("Label_PreferredList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in or sign up to keep track of the mixes you like..
        /// </summary>
        public static string Message_NoLikedMixes {
            get {
                return ResourceManager.GetString("Message_NoLikedMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mixes to be found here.
        /// </summary>
        public static string Message_NoMixesFound {
            get {
                return ResourceManager.GetString("Message_NoMixesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mixes found, make sure you&apos;re following someone to see what they&apos;re creating..
        /// </summary>
        public static string Message_NoMixesInFeed {
            get {
                return ResourceManager.GetString("Message_NoMixesInFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check back here after listening to some mixes..
        /// </summary>
        public static string Message_NoRecentlyPlayedMixes {
            get {
                return ResourceManager.GetString("Message_NoRecentlyPlayedMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tracks have been played recently for this mix..
        /// </summary>
        public static string Message_NoRecentlyPlayedTracks {
            get {
                return ResourceManager.GetString("Message_NoRecentlyPlayedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one&apos;s said anything about this mix yet..
        /// </summary>
        public static string Message_NoReviews {
            get {
                return ResourceManager.GetString("Message_NoReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person hasn&apos;t found any tracks they like yet..
        /// </summary>
        public static string Message_UserHasNoFavoriteTracks {
            get {
                return ResourceManager.GetString("Message_UserHasNoFavoriteTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user hasn&apos;t found anything they like yet..
        /// </summary>
        public static string Message_UserHasNoLikedMixes {
            get {
                return ResourceManager.GetString("Message_UserHasNoLikedMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person hasn&apos;t created any mixes..
        /// </summary>
        public static string Message_UserHasNoMixes {
            get {
                return ResourceManager.GetString("Message_UserHasNoMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person doesn&apos;t have any followers.
        /// </summary>
        public static string Message_UserNotFollowedByAnyone {
            get {
                return ResourceManager.GetString("Message_UserNotFollowedByAnyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person isn&apos;t following anyone..
        /// </summary>
        public static string Message_UserNotFollowingAnyone {
            get {
                return ResourceManager.GetString("Message_UserNotFollowingAnyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s no one following you..
        /// </summary>
        public static string Message_YouAreNotFollowedByAnyone {
            get {
                return ResourceManager.GetString("Message_YouAreNotFollowedByAnyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t found anyone to follow yet..
        /// </summary>
        public static string Message_YouAreNotFollowingAnyone {
            get {
                return ResourceManager.GetString("Message_YouAreNotFollowingAnyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t favorited any tracks yet, go listen to some music and star the ones you like!.
        /// </summary>
        public static string Message_YouHaveNoFavoriteTracks {
            get {
                return ResourceManager.GetString("Message_YouHaveNoFavoriteTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t liked any mixes yet..
        /// </summary>
        public static string Message_YouHaveNoLikedMixes {
            get {
                return ResourceManager.GetString("Message_YouHaveNoLikedMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t created any mixes yet, visit 8tracks.com on your computer to get started!.
        /// </summary>
        public static string Message_YouHaveNoMixes {
            get {
                return ResourceManager.GetString("Message_YouHaveNoMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like this app, please take a second to spread the word by giving it 5 stars!.
        /// </summary>
        public static string MessageBox_RateThisApp_Message {
            get {
                return ResourceManager.GetString("MessageBox_RateThisApp_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app?.
        /// </summary>
        public static string MessageBox_RateThisApp_Title {
            get {
                return ResourceManager.GetString("MessageBox_RateThisApp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait! If you sign out we will forget which mixes you played recently!.
        /// </summary>
        public static string MessageBox_ResetSettings_Message {
            get {
                return ResourceManager.GetString("MessageBox_ResetSettings_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out?.
        /// </summary>
        public static string MessageBox_ResetSettings_Title {
            get {
                return ResourceManager.GetString("MessageBox_ResetSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My mixes.
        /// </summary>
        public static string PreferredLists_Created {
            get {
                return ResourceManager.GetString("PreferredLists_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My liked mixes.
        /// </summary>
        public static string PreferredLists_Liked {
            get {
                return ResourceManager.GetString("PreferredLists_Liked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix feed.
        /// </summary>
        public static string PreferredLists_MixFeed {
            get {
                return ResourceManager.GetString("PreferredLists_MixFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Progress_Loading {
            get {
                return ResourceManager.GetString("Progress_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        public static string Progress_SigningIn {
            get {
                return ResourceManager.GetString("Progress_SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string Progress_Updating {
            get {
                return ResourceManager.GetString("Progress_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Beats.
        /// </summary>
        public static string Title_ApplicationName {
            get {
                return ResourceManager.GetString("Title_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixes.
        /// </summary>
        public static string Title_CreatedMixes {
            get {
                return ResourceManager.GetString("Title_CreatedMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracks.
        /// </summary>
        public static string Title_FavoriteTracks {
            get {
                return ResourceManager.GetString("Title_FavoriteTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followers.
        /// </summary>
        public static string Title_FollowedByUsers {
            get {
                return ResourceManager.GetString("Title_FollowedByUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to follows.
        /// </summary>
        public static string Title_FollowsUsers {
            get {
                return ResourceManager.GetString("Title_FollowsUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hot.
        /// </summary>
        public static string Title_HotMixes {
            get {
                return ResourceManager.GetString("Title_HotMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest mixes.
        /// </summary>
        public static string Title_LatestMixes {
            get {
                return ResourceManager.GetString("Title_LatestMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest tags.
        /// </summary>
        public static string Title_LatestTags {
            get {
                return ResourceManager.GetString("Title_LatestTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liked.
        /// </summary>
        public static string Title_LikedMixes {
            get {
                return ResourceManager.GetString("Title_LikedMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liked tags.
        /// </summary>
        public static string Title_LikedTags {
            get {
                return ResourceManager.GetString("Title_LikedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mix.
        /// </summary>
        public static string Title_Mix {
            get {
                return ResourceManager.GetString("Title_Mix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feed.
        /// </summary>
        public static string Title_MixFeed {
            get {
                return ResourceManager.GetString("Title_MixFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing.
        /// </summary>
        public static string Title_NowPlaying {
            get {
                return ResourceManager.GetString("Title_NowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to played.
        /// </summary>
        public static string Title_PlayedTracks {
            get {
                return ResourceManager.GetString("Title_PlayedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playing.
        /// </summary>
        public static string Title_Playing {
            get {
                return ResourceManager.GetString("Title_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popular.
        /// </summary>
        public static string Title_PopularMixes {
            get {
                return ResourceManager.GetString("Title_PopularMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent.
        /// </summary>
        public static string Title_RecentlyPlayedMixes {
            get {
                return ResourceManager.GetString("Title_RecentlyPlayedMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest.
        /// </summary>
        public static string Title_RecentMixes {
            get {
                return ResourceManager.GetString("Title_RecentMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reviews.
        /// </summary>
        public static string Title_Reviews {
            get {
                return ResourceManager.GetString("Title_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARE MIX.
        /// </summary>
        public static string Title_ShareMix {
            get {
                return ResourceManager.GetString("Title_ShareMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string Title_Tags {
            get {
                return ResourceManager.GetString("Title_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followers.
        /// </summary>
        public static string Title_YouAreFollowedBy {
            get {
                return ResourceManager.GetString("Title_YouAreFollowedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to following.
        /// </summary>
        public static string Title_YouFollow {
            get {
                return ResourceManager.GetString("Title_YouFollow", resourceCulture);
            }
        }
    }
}
