//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatBeats {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlatBeats.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email mix.
        /// </summary>
        internal static string Command_EmailMix {
            get {
                return ResourceManager.GetString("Command_EmailMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like.
        /// </summary>
        internal static string Command_LikeMix {
            get {
                return ResourceManager.GetString("Command_LikeMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        internal static string Command_NextTrack {
            get {
                return ResourceManager.GetString("Command_NextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        internal static string Command_PauseMix {
            get {
                return ResourceManager.GetString("Command_PauseMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        internal static string Command_PinToStart {
            get {
                return ResourceManager.GetString("Command_PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        internal static string Command_PlayMix {
            get {
                return ResourceManager.GetString("Command_PlayMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share mix.
        /// </summary>
        internal static string Command_ShareMix {
            get {
                return ResourceManager.GetString("Command_ShareMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlike.
        /// </summary>
        internal static string Command_UnlikeMix {
            get {
                return ResourceManager.GetString("Command_UnlikeMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix: {0}
        ///Description:
        ///{1}
        ///Link:
        ///{2}.
        /// </summary>
        internal static string EmailBody_ShareMix {
            get {
                return ResourceManager.GetString("EmailBody_ShareMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out this 8tracks.com Mix!.
        /// </summary>
        internal static string EmailSubject_ShareMix {
            get {
                return ResourceManager.GetString("EmailSubject_ShareMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in or sign up to keep track of the mixes you like..
        /// </summary>
        internal static string Message_NoLikedMixes {
            get {
                return ResourceManager.GetString("Message_NoLikedMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hot.
        /// </summary>
        internal static string Title_HotMixes {
            get {
                return ResourceManager.GetString("Title_HotMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest mixes.
        /// </summary>
        internal static string Title_LatestMixes {
            get {
                return ResourceManager.GetString("Title_LatestMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liked.
        /// </summary>
        internal static string Title_LikedMixes {
            get {
                return ResourceManager.GetString("Title_LikedMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popular.
        /// </summary>
        internal static string Title_PopularMixes {
            get {
                return ResourceManager.GetString("Title_PopularMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent.
        /// </summary>
        internal static string Title_RecentlyPlayedMixes {
            get {
                return ResourceManager.GetString("Title_RecentlyPlayedMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest.
        /// </summary>
        internal static string Title_RecentMixes {
            get {
                return ResourceManager.GetString("Title_RecentMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARE MIX.
        /// </summary>
        internal static string Title_ShareMix {
            get {
                return ResourceManager.GetString("Title_ShareMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        internal static string Title_Tags {
            get {
                return ResourceManager.GetString("Title_Tags", resourceCulture);
            }
        }
    }
}
